export const CONSTS_UTILS_EMPTY_STRING = '';
export const CONSTS_UTILS_FILE_EXTENSION_JSON = '.json';
export const CONSTS_UTILS_PERIOD_STRING = '.';
export const CONSTS_UTILS_PROP_VALUE_NOT_FOUND = 'PROP_VALUE_NOT_FOUND';
